# -*- coding: utf-8 -*-
"""generate_requirements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k7ffRQ6xpA3VgT9RrswxDQ50Szx4ipjp

This file is meant to generate a requirements.txt file as required to run the code in repository social_media_tools on GitHub account austindesosa
"""

import os
from time import time

t_start = time() + 0.0

os.system('pip install pydub')
os.system('sudo apt-get install python-pyaudio python3-pyaudio')
os.system('sudu apt-get install python3 python-all-dev python3')
os.system('pip install SpeechRecognition')
os.system('pip install -U textblob')
os.system('pip install instaloader')

t_install = time() - t_start

print(f'Installation time : {t_install} seconds')

os.system('pip freeze > requirements.txt')