# -*- coding: utf-8 -*-
"""quickstart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R3iq1Bw8P0LSx82dFmnUQ3Vb7lLJZFRF

This file is meant as a standalone file which can set up the entire GitHub repo **social_media_tools** by GitHub user **austindesosa**.
Put it in the same directory as a Google Colab notebook, and invoke the Python code

from quickstart import *

so as to conveniently import all modules without having to use the command line


"""

import os
os.system('git clone https://www.github.com/austindesosa/social_media_tools')
os.system('mv -v /content/social_media_tools/* /content/')
from social_media_tool import *
