# -*- coding: utf-8 -*-
"""tf_cat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iLiq9w6MaxWIiizcYyEuwcCu-Et8J4nl

The following is an implementation of a simple binary classifier in TensorFlow to classify images as either cat or non-cat images.
Inspired by Andrew Ng of Coursera in his course on "Neural Networks and Deep Learning"
However, that classifier is written in pure NumPy, while this one is written using TensorFlow
"""

import os
import glob
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten
import json

model = Sequential()

model.add(Flatten())
model.add( Dense(20,activation='relu') )
model.add( Dense(7,activation='relu') )
model.add( Dense(5,activation='relu') )
model.add( Dense(1,activation='sigmoid') )

#model.compile(optimizer='SGD', loss = 'categorical_crossentropy')

with open('tf_cat.json', 'w') as f:
  f.write(json.loads(json.dumps(model.to_json())))